### ISSUE TITLE
PULL_REQUEST_TEMPLATE: Update with new task list items

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#973]
**Details of the scenario you tried and the problem that is occurring:**
I suggest we update the task list with a few items and clarify already existing. This list is updated to reflect review comments I often have to do (here and in xFailOverCluster), so I'm hoping this helps contributors from getting one less review comment from reviewers. 😄 
 
I suggest we update with this new task list in PULL_REQUEST_TEMPLATE.md. Not all of these should be checked for each PR, and it already says in a comment in the PULL_REQUEST_TEMPLATE.md; 'Change to [x] for each task in the task list that applies to this PR'.

- [ ] Added an entry under the Unreleased section in CHANGELOG.md?
- [ ] Resource documentation added/updated in README.md?
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based help?
- [ ] Comment-based help added/updated?
- [ ] Localization strings added/updated?
- [ ] Examples appropriately added/updated?
- [ ] Unit tests added/updated? See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where applicable)? See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to Style Guidelines? See [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev
